import React from 'react'
import Head from 'next/head'
import { Header } from './Header'

function MainLayout({ children }) {

   return (
      <>
         <Head>
            <title>BlueTrade.</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
            <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" />
         </Head>
         <header>
            <Header />
         </header>
         <main >
            {children}
         </main>
      </>
   )
}

export default MainLayout

